on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: Pull and Build
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
    - name: Connect, Pull, and Build
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ${{ secrets.WORK_DIR }} &&
          git checkout ${{ secrets.MAIN_BRANCH }} &&
          git pull &&
          if ! command -v npm &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&
            sudo apt install -y nodejs
          fi &&
          npm install &&
          npm run build
        "
        
    - name: Cleanup
      run: rm -rf ~/.ssh
